version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./volumes/sql_data:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
